version: '3'
services:
  mongodb:
    image: mongo:5.0.17
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - rsvpnet

  rsvp_spring:
    image: registry.cloudyuga.guru/library/rsvp_springboot:v1
    environment:
      MONGODB_HOST: mongodb
    ports:
      - "80:8080"
    networks:
      - rsvpnet

networks:
  rsvpnet:

volumes:
  db_data:
