version: '3.8'
services:
  mongodb:
    image: mongo:3.3
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - rsvpnet

  rsvp_spring:
    image: oshi36/rsvp_springboot:autoinstru
    environment:
      - MONGODB_HOST=mongodb
      - OTEL_SERVICE_NAME=rsvp_spring
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
    ports:
      - "80:8080"
    networks:
      - rsvpnet
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "30000:16686"
      - "14250:14250"
    networks:
      - rsvpnet  

networks:
  rsvpnet:

volumes:
  db_data:
